#!/usr/bin/env python3
"""
Daily Operations Report Script
Generates and sends daily operational reports via Feishu
"""

import os
import sys
import json
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, Any

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent.absolute()))

try:
    from main_service_enhanced import EnhancedAICustomerService
    from services.feishu_notifier import FeishuNotifier
except ImportError as e:
    print(f"Failed to import required modules: {e}")
    print("Make sure all dependencies are installed.")
    sys.exit(1)


def collect_metrics(service: EnhancedAICustomerService) -> Dict[str, Any]:
    """
    Collect system metrics for the report
    
    Args:
        service: Initialized service instance
        
    Returns:
        Dictionary of metrics
    """
    metrics = {
        "report_date": datetime.now().strftime("%Y-%m-%d"),
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    
    try:
        # Get health status
        health = service.get_system_health()
        metrics["system_status"] = health["status"]
        metrics["healthy_components"] = sum(1 for c in health["components"].values() if c["status"] == "healthy")
        metrics["total_components"] = len(health["components"])
        
        # Get knowledge base stats
        kb_stats = service.list_knowledge_bases()
        metrics["knowledge_bases"] = kb_stats.get("count", 0)
        
        # Get LLM providers
        if service.llm_manager:
            metrics["llm_providers"] = service.llm_manager.list_providers()
        else:
            metrics["llm_providers"] = []
        
        # Calculate uptime (simplified - from service start)
        # In production, this would come from monitoring system
        metrics["service_uptime"] = "N/A"
        
        # System resources (basic)
        try:
            import psutil
            process = psutil.Process(os.getpid())
            metrics["memory_usage_mb"] = round(process.memory_info().rss / 1024 / 1024, 2)
            metrics["cpu_percent"] = process.cpu_percent(interval=1)
        except ImportError:
            metrics["memory_usage_mb"] = "psutil not available"
            metrics["cpu_percent"] = "psutil not available"
        
    except Exception as e:
        print(f"Error collecting metrics: {e}")
        metrics["error"] = str(e)
    
    return metrics


def generate_report_text(metrics: Dict[str, Any]) -> str:
    """
    Generate human-readable report text
    
    Args:
        metrics: Metrics dictionary
        
    Returns:
        Formatted markdown report
    """
    report_date = metrics.get("report_date", "N/A")
    
    lines = [
        f"# 📊 Daily Operations Report - {report_date}",
        "",
        "## System Overview",
        f"- **Status**: {metrics.get('system_status', 'unknown').upper()}",
        f"- **Healthy Components**: {metrics.get('healthy_components', 0)}/{metrics.get('total_components', 0)}",
        f"- **Knowledge Bases**: {metrics.get('knowledge_bases', 0)}",
        f"- **LLM Providers**: {', '.join(metrics.get('llm_providers', ['None']))}",
        "",
        "## Resource Usage",
    ]
    
    memory = metrics.get('memory_usage_mb', 'N/A')
    cpu = metrics.get('cpu_percent', 'N/A')
    lines.extend([
        f"- **Memory**: {memory} MB",
        f"- **CPU**: {cpu}%",
        ""
    ])
    
    lines.extend([
        "## Configuration",
        f"- **Generated**: {metrics.get('generated_at', 'N/A')}",
        f"- **Time Zone**: Asia/Shanghai (GMT+8)",
        "",
        "---",
        "*This report is automatically generated by the AI Customer Service System.*"
    ])
    
    return "\n".join(lines)


def main():
    """
    Main function to generate and send daily report
    """
    print("Starting daily report generation...")
    
    # Initialize service
    try:
        service = EnhancedAICustomerService()
        print("Service initialized")
    except Exception as e:
        print(f"Failed to initialize service: {e}")
        sys.exit(1)
    
    # Collect metrics
    print("Collecting metrics...")
    metrics = collect_metrics(service)
    
    # Generate report
    report_text = generate_report_text(metrics)
    print("Report generated:")
    print("-" * 40)
    print(report_text)
    print("-" * 40)
    
    # Save report to file
    report_dir = Path("./reports")
    report_dir.mkdir(exist_ok=True)
    report_file = report_dir / f"daily_report_{datetime.now().strftime('%Y-%m-%d')}.md"
    
    with open(report_file, 'w', encoding='utf-8') as f:
        f.write(report_text)
    print(f"Report saved to: {report_file}")
    
    # Send via Feishu if configured
    if service.feishu_notifier:
        print("Sending report via Feishu...")
        result = service.feishu_notifier.send_daily_report(metrics)
        if result.get("success"):
            print("✓ Report sent successfully")
        else:
            print(f"✗ Failed to send report: {result.get('error')}")
    else:
        print("Feishu notifier not configured. Report not sent.")
    
    print("Daily report generation complete.")
    return metrics


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted by user")
        sys.exit(130)
    except Exception as e:
        print(f"Fatal error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)