"""
Billing Settlement Script for AI Customer Service System
Handles monthly billing and subscription renewals
"""

import sys
import os
from datetime import datetime, timedelta
from pathlib import Path
import json

# Setup directories
project_root = Path(__file__).parent.parent
LOGS_DIR = project_root / "logs"
LOGS_DIR.mkdir(exist_ok=True)
DATA_DIR = project_root / "data"
DATA_DIR.mkdir(exist_ok=True)


def log_to_file(message: str, log_file: str = "billing.log"):
    """Write log to local file"""
    log_path = LOGS_DIR / log_file
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(f"[{timestamp}] {message}\n")


def load_billing_data():
    """Load billing data"""
    billing_file = DATA_DIR / "billing_records.json"
    if billing_file.exists():
        try:
            with open(billing_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            log_to_file(f"Failed to load billing data: {str(e)}", "errors.log")
    return {"invoices": [], "subscriptions": []}


def save_billing_data(data):
    """Save billing data"""
    billing_file = DATA_DIR / "billing_records.json"
    try:
        with open(billing_file, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
    except Exception as e:
        log_to_file(f"Failed to save billing data: {str(e)}", "errors.log")


def generate_monthly_billing():
    """Generate monthly billing"""
    now = datetime.now()
    current_month = now.strftime("%Y-%m")
    last_month = (now.replace(day=1) - timedelta(days=1)).strftime("%Y-%m")
    
    try:
        billing_data = load_billing_data()
        
        # Simulate billing calculation
        # In production, query from database
        invoice = {
            "id": f"INV-{current_month}-{len(billing_data['invoices']) + 1:04d}",
            "month": last_month,
            "generated_at": now.isoformat(),
            "total_amount": 0.0,
            "status": "pending",
            "items": []
        }
        
        # Add invoice to records
        billing_data["invoices"].append(invoice)
        save_billing_data(billing_data)
        
        # Generate report
        report_content = f"""# Monthly Billing Report

**Billing Month**: {last_month}  
**Generated**: {now.strftime("%Y-%m-%d %H:%M:%S")}  
**Invoice ID**: {invoice['id']}

---

## Summary

| Item | Value |
|------|-------|
| Total Amount | ${invoice['total_amount']:.2f} |
| Status | {invoice['status']} |
| Subscriptions Processed | 0 |
| Renewals Successful | 0 |
| Failed Renewals | 0 |

## Details

*No active subscriptions in current billing period*

---

*Auto-generated by billing system*
"""

        # Save report
        report_file = LOGS_DIR / f"billing_report_{last_month}.md"
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(report_content)
        
        log_to_file(f"Billing report generated: {report_file}")
        print("[SUCCESS] Billing settlement completed!")
        print(f"Report file: {report_file}")
        
        return True, invoice
        
    except Exception as e:
        error_msg = f"Billing settlement failed: {str(e)}"
        log_to_file(error_msg, "errors.log")
        print(f"[ERROR] {error_msg}")
        import traceback
        traceback.print_exc()
        return False, {}


def main():
    """Main function"""
    log_to_file("="*50)
    log_to_file("Starting monthly billing settlement")
    
    try:
        success, invoice = generate_monthly_billing()
        if success:
            log_to_file("Billing settlement completed")
            return 0
        else:
            log_to_file("Billing settlement failed")
            return 1
    except Exception as e:
        error_msg = f"Main exception: {str(e)}"
        log_to_file(error_msg, "errors.log")
        print(f"[ERROR] {error_msg}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    exit(main())
