"""
Daily Report Generator for AI Customer Service System
Standalone script with no external dependencies
"""

import sys
# Fix Windows console encoding for UTF-8 output
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

import os
from datetime import datetime, timedelta
from pathlib import Path
import json

# Setup directories
project_root = Path(__file__).parent.parent
LOGS_DIR = project_root / "logs"
LOGS_DIR.mkdir(exist_ok=True)
DATA_DIR = project_root / "data"
DATA_DIR.mkdir(exist_ok=True)


def log_to_file(message: str, log_file: str = "daily_report.log"):
    """Write log to local file"""
    log_path = LOGS_DIR / log_file
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(f"[{timestamp}] {message}\n")


def load_stats_data():
    """Load statistics data"""
    stats_file = DATA_DIR / "system_stats.json"
    if stats_file.exists():
        try:
            with open(stats_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            log_to_file(f"Failed to load stats: {str(e)}", "errors.log")
    return {}


def save_stats_data(stats):
    """Save statistics data"""
    stats_file = DATA_DIR / "system_stats.json"
    try:
        with open(stats_file, "w", encoding="utf-8") as f:
            json.dump(stats, f, ensure_ascii=False, indent=2)
    except Exception as e:
        log_to_file(f"Failed to save stats: {str(e)}", "errors.log")


def generate_daily_report():
    """Generate daily report"""
    yesterday = datetime.utcnow() - timedelta(days=1)
    date_str = yesterday.strftime("%Y-%m-%d")
    today_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    try:
        # Load historical stats
        all_stats = load_stats_data()
        yesterday_stats = all_stats.get(date_str, {})
        
        # Statistics (in production, query from database)
        stats = {
            "date": date_str,
            "new_users": yesterday_stats.get("new_users", 0),
            "active_conversations": yesterday_stats.get("active_conversations", 0),
            "knowledge_base_count": yesterday_stats.get("knowledge_base_count", 0),
            "llm_calls": yesterday_stats.get("llm_calls", 0),
            "revenue": yesterday_stats.get("revenue", 0.0),
            "system_status": "Running"
        }

        # Generate report content
        report_content = f"""# AI Customer Service System Daily Report

**Report Date**: {date_str}  
**Generated**: {today_str}

---

## Core Metrics

| Metric | Value |
|--------|-------|
| New Users | {stats['new_users']} |
| Conversations | {stats['active_conversations']} |
| Knowledge Base | {stats['knowledge_base_count']} fragments |
| LLM Calls | {stats['llm_calls']} |
| Revenue | ${stats['revenue']:.2f} |

## System Status

- Vector DB: Running
- API Service: Running
- Scheduled Tasks: Running

---

*Auto-generated by system*
"""

        # Save report to file
        report_file = LOGS_DIR / f"daily_report_{date_str}.md"
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(report_content)

        # Update stats
        all_stats[date_str] = stats
        save_stats_data(all_stats)

        log_to_file(f"Report generated: {report_file}")
        print("[SUCCESS] Daily report generated!")
        print(f"Report file: {report_file}")
        print(f"\nReport preview:")
        print("="*60)
        print(report_content)
        print("="*60)
        
        return True, stats
        
    except Exception as e:
        error_msg = f"Report generation failed: {str(e)}"
        log_to_file(error_msg, "errors.log")
        print(f"[ERROR] {error_msg}")
        import traceback
        traceback.print_exc()
        return False, {}


def main():
    """Main function"""
    log_to_file("="*50)
    log_to_file("Starting daily report generation")
    
    try:
        success, stats = generate_daily_report()
        if success:
            log_to_file("Report generation completed")
            return 0
        else:
            log_to_file("Report generation failed")
            return 1
    except Exception as e:
        error_msg = f"Main exception: {str(e)}"
        log_to_file(error_msg, "errors.log")
        print(f"[ERROR] {error_msg}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    exit(main())
