"""
Data Cleanup Script for AI Customer Service System
Cleans temporary files and archives old data
"""

import sys
import os
from datetime import datetime, timedelta
from pathlib import Path
import shutil
import json

# Setup directories
project_root = Path(__file__).parent.parent
LOGS_DIR = project_root / "logs"
LOGS_DIR.mkdir(exist_ok=True)
DATA_DIR = project_root / "data"
DATA_DIR.mkdir(exist_ok=True)
TEMP_DIR = project_root / "temp"
TEMP_DIR.mkdir(exist_ok=True)
ARCHIVE_DIR = project_root / "archive"
ARCHIVE_DIR.mkdir(exist_ok=True)


def log_to_file(message: str, log_file: str = "cleanup.log"):
    """Write log to local file"""
    log_path = LOGS_DIR / log_file
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(f"[{timestamp}] {message}\n")


def cleanup_temp_files():
    """Clean up temporary files"""
    cleaned_count = 0
    cleaned_size = 0
    
    try:
        # Clean temp directory
        if TEMP_DIR.exists():
            for item in TEMP_DIR.iterdir():
                try:
                    if item.is_file():
                        file_size = item.stat().st_size
                        item.unlink()
                        cleaned_count += 1
                        cleaned_size += file_size
                    elif item.is_dir():
                        dir_size = sum(f.stat().st_size for f in item.rglob('*') if f.is_file())
                        shutil.rmtree(item)
                        cleaned_count += 1
                        cleaned_size += dir_size
                except Exception as e:
                    log_to_file(f"Failed to remove {item}: {str(e)}", "errors.log")
        
        return cleaned_count, cleaned_size
    except Exception as e:
        log_to_file(f"Temp cleanup error: {str(e)}", "errors.log")
        return 0, 0


def archive_old_logs(days: int = 30):
    """Archive old log files"""
    archived_count = 0
    cutoff_date = datetime.now() - timedelta(days=days)
    
    try:
        archive_subdir = ARCHIVE_DIR / "logs" / cutoff_date.strftime("%Y-%m")
        archive_subdir.mkdir(parents=True, exist_ok=True)
        
        if LOGS_DIR.exists():
            for log_file in LOGS_DIR.glob("*.log"):
                try:
                    file_mtime = datetime.fromtimestamp(log_file.stat().st_mtime)
                    if file_mtime < cutoff_date:
                        dest = archive_subdir / log_file.name
                        shutil.move(str(log_file), str(dest))
                        archived_count += 1
                except Exception as e:
                    log_to_file(f"Failed to archive {log_file}: {str(e)}", "errors.log")
        
        return archived_count
    except Exception as e:
        log_to_file(f"Archive error: {str(e)}", "errors.log")
        return 0


def perform_cleanup():
    """Perform data cleanup"""
    now = datetime.now()
    
    try:
        # Clean temp files
        temp_count, temp_size = cleanup_temp_files()
        
        # Archive old logs
        archived_logs = archive_old_logs(days=30)
        
        # Generate report
        report_content = f"""# Data Cleanup Report

**Cleanup Date**: {now.strftime("%Y-%m-%d %H:%M:%S")}  
**Type**: Weekly Maintenance

---

## Cleanup Summary

| Task | Result |
|------|--------|
| Temp Files Removed | {temp_count} files |
| Space Freed | {temp_size / 1024:.2f} KB |
| Old Logs Archived | {archived_logs} files |

## Directories Cleaned

- Temp Directory: {TEMP_DIR}
- Logs Archived To: {ARCHIVE_DIR / "logs"}

## System Status

- Vector DB: Running
- API Service: Running
- Storage: Optimized

---

*Auto-generated by cleanup system*
"""

        # Save report
        report_file = LOGS_DIR / f"cleanup_report_{now.strftime('%Y-%m-%d')}.md"
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(report_content)
        
        log_to_file(f"Cleanup completed: {temp_count} temp files removed, {archived_logs} logs archived")
        print("[SUCCESS] Data cleanup completed!")
        print(f"Temp files removed: {temp_count}")
        print(f"Space freed: {temp_size / 1024:.2f} KB")
        print(f"Logs archived: {archived_logs}")
        print(f"Report file: {report_file}")
        
        return True, {
            "temp_removed": temp_count,
            "space_freed_kb": temp_size / 1024,
            "logs_archived": archived_logs
        }
        
    except Exception as e:
        error_msg = f"Cleanup failed: {str(e)}"
        log_to_file(error_msg, "errors.log")
        print(f"[ERROR] {error_msg}")
        import traceback
        traceback.print_exc()
        return False, {}


def main():
    """Main function"""
    log_to_file("="*50)
    log_to_file("Starting data cleanup")
    
    try:
        success, stats = perform_cleanup()
        if success:
            log_to_file("Cleanup completed successfully")
            return 0
        else:
            log_to_file("Cleanup failed")
            return 1
    except Exception as e:
        error_msg = f"Main exception: {str(e)}"
        log_to_file(error_msg, "errors.log")
        print(f"[ERROR] {error_msg}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    exit(main())
